from unaiverse.agent import Agent
from unaiverse.networking.node.node import Node

# Agent (the world master; it will be assigned the "teacher" role and buffers data generated by others)
agent = Agent(proc=None, buffer_generated_by_others="one")

# Node hosting agent
node = Node(agent, node_name="DigitClassifier1", hidden=True, clock_delta=1. / 15.)

# Running node
node.run(join_world="DigitSocialLearning")
