"""
 █████  █████ ██████   █████           █████ █████   █████ ██████████ ███████████    █████████  ██████████
░░███  ░░███ ░░██████ ░░███           ░░███ ░░███   ░░███ ░░███░░░░░█░░███░░░░░███  ███░░░░░███░░███░░░░░█
 ░███   ░███  ░███░███ ░███   ██████   ░███  ░███    ░███  ░███  █ ░  ░███    ░███ ░███    ░░░  ░███  █ ░
 ░███   ░███  ░███░░███░███  ░░░░░███  ░███  ░███    ░███  ░██████    ░██████████  ░░█████████  ░██████
 ░███   ░███  ░███ ░░██████   ███████  ░███  ░░███   ███   ░███░░█    ░███░░░░░███  ░░░░░░░░███ ░███░░█
 ░███   ░███  ░███  ░░█████  ███░░███  ░███   ░░░█████░    ░███ ░   █ ░███    ░███  ███    ░███ ░███ ░   █
 ░░████████   █████  ░░█████░░████████ █████    ░░███      ██████████ █████   █████░░█████████  ██████████
  ░░░░░░░░   ░░░░░    ░░░░░  ░░░░░░░░ ░░░░░      ░░░      ░░░░░░░░░░ ░░░░░   ░░░░░  ░░░░░░░░░  ░░░░░░░░░░
           A Collectionless AI Project (https://collectionless.ai)
           Registration/Login: https://unaiverse.io
           Code Repositories:  https://github.com/collectionlessai/
           Main Developers:    Stefano Melacci (Project Leader), Christian Di Maio, Tommaso Guidi
"""

import os
from typing import Any, List, Tuple
from unaiverse.utils.logger import log
from unaiverse.agent import Agent
from unaiverse.utils.misc import prepare_app_dir
from unaiverse.interaction import CompletionReason, Interaction
from unaiverse.modules.utils import error_rate_mnist_test_set
from unaiverse.agent import action


"""Role: student (generated by hsm-builder).

Edit this file to add action methods referenced by student.json.
"""

class WAgent(Agent):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)

        self._exam = []
        self._teacher = None

    @action                                                                                                                                           
    async def process(self, interaction: Interaction | None = None) -> bool:                                                                        
        _, _, _, stdout_bindings = self.get_default_stream_bindings(public=False)                                                                     
        if stdout_bindings:                                                                                                                           
            self.stdout.bind(stdout_bindings, uuid=interaction.uuid if interaction else None)                                                         
        return await super().process(interaction=interaction)                                                                                         
                                                                                                                                                      
    @action
    async def learn(self, interaction: Interaction | None = None) -> bool:
        _, _, _, stdout_bindings = self.get_default_stream_bindings(public=False)
        if stdout_bindings:
            self.stdout.bind(stdout_bindings, uuid=interaction.uuid if interaction else None)
        return await super().learn(interaction=interaction)