"""
 █████  █████ ██████   █████           █████ █████   █████ ██████████ ███████████    █████████  ██████████
░░███  ░░███ ░░██████ ░░███           ░░███ ░░███   ░░███ ░░███░░░░░█░░███░░░░░███  ███░░░░░███░░███░░░░░█
 ░███   ░███  ░███░███ ░███   ██████   ░███  ░███    ░███  ░███  █ ░  ░███    ░███ ░███    ░░░  ░███  █ ░
 ░███   ░███  ░███░░███░███  ░░░░░███  ░███  ░███    ░███  ░██████    ░██████████  ░░█████████  ░██████
 ░███   ░███  ░███ ░░██████   ███████  ░███  ░░███   ███   ░███░░█    ░███░░░░░███  ░░░░░░░░███ ░███░░█
 ░███   ░███  ░███  ░░█████  ███░░███  ░███   ░░░█████░    ░███ ░   █ ░███    ░███  ███    ░███ ░███ ░   █
 ░░████████   █████  ░░█████░░████████ █████    ░░███      ██████████ █████   █████░░█████████  ██████████
  ░░░░░░░░   ░░░░░    ░░░░░  ░░░░░░░░ ░░░░░      ░░░      ░░░░░░░░░░ ░░░░░   ░░░░░  ░░░░░░░░░  ░░░░░░░░░░
           A Collectionless AI Project (https://collectionless.ai)
           Registration/Login: https://unaiverse.io
           Code Repositories:  https://github.com/collectionlessai/
           Main Developers:    Stefano Melacci (Project Leader), Christian Di Maio, Tommaso Guidi
"""

import os
from typing import Any, List, Tuple
from unaiverse.utils.logger import log
from unaiverse.agent import Agent
from unaiverse.utils.misc import prepare_app_dir
from unaiverse.interaction import CompletionReason, Interaction
from unaiverse.modules.utils import error_rate_mnist_test_set
import torch
import random as rand


"""Role: student (generated by hsm-builder).

Edit this file to add action methods referenced by student.json.
"""

class WAgent(Agent):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        # Role-specific memory attributes — initialise state variables here.
        # Convention: self._something = None  (underscore prefix).
        # Example:    self._exam = None
        self._agent_id = rand.choices("abcdefghijklmnopqrstuvwxyz0123456789", k=8)
        self._agent_folder_name = os.path.join(
            prepare_app_dir(), "task_incremental_learning", "asdfasdfasdf"
        )
        os.makedirs(self._agent_folder_name, exist_ok=True)

        self._exam = []  # This will hold the current exam interaction, if any
        self._teacher = None  # This will hold the teacher agent id, if connected

    
    async def connect_to_the_teacher(self):
        log.user(f"Student {self._agent_id} is looking for the teacher...")
        result: List[str] = self.get_agents_by_role("teacher", handshake_completed=True)
        log.user(f"Student {self._agent_id} found teachers: {result}")
        if not result:
            return False
        teacher = result[0]
        self._teacher = teacher
        result = await self.connect_to(teacher)
        log.user(f"Student {self._agent_id} connection to teacher {teacher} result: {result}")
        return result